apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-agent
  namespace: default
  labels:
    app: portainer-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portainer-agent
  template:
    metadata:
      labels:
        app: portainer-agent
    spec:
      containers:
        - name: portainer-agent
          image: portainer/agent:latest
          ports:
            - containerPort: 9001
          env:
            - name: AGENT_CLUSTER_ADDR
              value: "tasks.portainer-agent"
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
