apiVersion: v1
kind: Service
metadata:
  name: portainer-agent
  namespace: default
  labels:
    app: portainer
spec:
  type: LoadBalancer
  selector:
    app: portainer-agent
  ports:
    - protocol: TCP
      port: 9001       # The port to access the Portainer Agent
      targetPort: 9001 # The port used by the Portainer Agent container
