apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: glance
  name: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: glance
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: glance
    spec:
      nodeSelector: #only do this if you need this to run on a specific node other comment out these two lines 
        kubernetes.io/hostname: kube-prod-worker-1 # comnent this out if not needed
      containers:
        - image: glanceapp/glance
          name: glance
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/glance.yml
              name: glance-claim0
            - mountPath: /etc/timezone
              name: glance-cm1
              readOnly: true
              subPath: timezone
            - mountPath: /etc/localtime
              name: glance-cm2
              readOnly: true
              subPath: localtime
      restartPolicy: Always
      volumes:
        - name: glance-claim0
          hostPath:
            path: /root/data/glance/glance.yml # Change "yourusername" accordingly. This is where the glance.yml file is located 
            type: File
        - configMap:
            items:
              - key: timezone
                path: timezone
            name: glance-cm1
          name: glance-cm1
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: glance-cm2
          name: glance-cm2
