apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: glance
  name: glance
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: glance
