apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring  # Adjust if Grafana is in a different namespace
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 80           # External port for the LoadBalancer
      targetPort: 3000   # Internal port Grafana listens on
      protocol: TCP
      name: http