apiVersion: traefik.io/v1alpha1
kind: ingressRoute
metadata:
  name: nginx-ingressroute
  namespace: default
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  entrypoints:
  - websecure
  routes:
  - match: Host(`nginx.kube.local.soulneko.xyz`)
    kind: Rule
    services:
    - name: nginx
      port: 80

  # roles:
  #   - host: nginx.kube.soulneko.xyz
  #     http:
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #           backend: 
  #             service:
  #               name: nginx
  #               port:
  #                 number: 80

