apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
  namespace: guacamole
  labels:
    app: guacamole
    
spec:
  type: LoadBalancer
 # loadBalancerIP: <STATIC_IP>  # Replace <STATIC_IP> with your desired static IP if your cloud provider supports it
  ports:
  - port: 80
    targetPort: 8080  # Port of the Guacamole web interface
    protocol: TCP
  selector:
    app: guacamole
