apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexterm
  name: nexterm-service
  namespace: nexterm
spec:
  type: LoadBalancer
  ports:
    - name: "6989"
      port: 6989
      protocol: TCP
      targetPort: 6989
  selector:
    app: nexterm
