apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: nexterm
  name: nexterm
  namespace: nexterm
spec:
  ports:
    - name: "6989"
      port: 6989
      targetPort: 6989
  selector:
    io.kompose.service: nexterm
