apiVersion: v1
kind: Service
metadata:
  name: ansible-semaphore-service
  namespace: semaphore
  labels:
    app: semaphore
spec:
  type: LoadBalancer
  selector:
    app: semaphore
  ports:
    - name: http
      protocol: TCP
      port: 80     # External port
      targetPort: 3000