apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  labels:
    app: prowlarr
spec:
  type: LoadBalancer
  selector:
    app: qbittorrent
    component: prowlarr  # Match the specific label for Prowlarr
  ports:
    - protocol: TCP
      port: 9696         # External port to expose
      targetPort: 9696    # Port on the container
