apiVersion: v1
kind: Service
metadata:
  name: beszel-service
  labels:
    app: beszel
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.10.22  # Replace <STATIC_IP> with your desired IP if your cloud provider supports static IPs
  selector:
    app: beszel
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 8090  # Container's port
