---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-domain-xyz
  namespace: default
spec:
  secretName: kube-domain-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.kube.domain.local"
  dnsNames:
  - "kube.domain.local"
  - "*.kube.domain.local"