apiVersion: v1
kind: Service
metadata:
  labels:
    app: homepage
  name: homepage-service
  namespace: homepage
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: homepage