authentik:
    secret_key: "NC2as3vaySVhJfw3TlQXlZUJa5DrnkTv8cygH/snImJPB7wn235onBULf9atS09dglpirJGi39gvyOrb"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "XgQcOAlh88iyCNDittUxHM4HOp84E1hMPecfSeqgb1wyhFV6Zb"

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: nginx
        enabled: true
        hosts:
            - authentik.soulneko.xyz

postgresql:
    enabled: true
    auth:
        password: "XgQcOAlh88iyCNDittUxHM4HOp84E1hMPecfSeqgb1wyhFV6Zb"
redis:
    enabled: true
