apiVersion: v1
kind: Namespace
metadata:
  name: kwatch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kwatch
  namespace: kwatch
data:
  config.yaml: |
    maxRecentLogLines: 20
    ignoreFailedGracefulShutdown: true
    alert:
      slack:
        webhook: <webhook>
    #namespaces:
    #  - <optional_namespace>
    nodeMonitor:
        enabled: true
