---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      nodeSelector: 
        kubernetes.io/hostname: kube-prod-worker-5
      containers:
      - image: jellyfin/jellyfin
        imagePullPolicy: Always
        name: jellyfin
        resources:
          limits:
            gpu.intel.com/i915: "1" # requesting 1 GPU
        ports:
        - containerPort: 8096
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: Europe/London
        volumeMounts:
        - mountPath: "/books"
          readOnly: false
          name: smb
          subPath: Audiobooks
        - mountPath: "/movies"
          readOnly: false
          name: smb
          subPath: Films
        - mountPath: "/anime"
          readOnly: false
          name: smb
          subPath: TVShows
        - mountPath: "/music"
          readOnly: false
          name: smb
          subPath: Music
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-jellyfin-smb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin 
spec:
  ports:
  - name: web-tcp
    port: 8096
    protocol: TCP
    targetPort: 8096
  - name: web-udp
    port: 8096
    protocol: UDP
    targetPort: 8096
  selector:
    app: jellyfin